linters:
  enable:
    - goimports
    - revive
    - gofmt
    - misspell
    - depguard

linters-settings:
  errcheck:
    exclude: ./.errcheck-exclude
  goimports:
    local-prefixes: "github.com/56quarters/roger"
