{
 "title": "Roger Overview",
 "tags": [
  "roger",
  "dns",
  "network",
  "linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "net_interface",
    "query": {
     "query": "label_values(roger_net_rx_bytes{interface!=\"lo\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNS Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(roger_dns_cache_hits[$__rate_interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(roger_dns_cache_misses[$__rate_interval])",
     "legendFormat": "misses"
    },
    {
     "expr": "rate(roger_dns_cache_insertions[$__rate_interval])",
     "legendFormat": "inserts"
    },
    {
     "expr": "rate(roger_dns_cache_evictions[$__rate_interval])",
     "legendFormat": "evictions"
    }
   ]
  },
  {
   "title": "Tracked Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(roger_nf_conntrack_entries[$__rate_interval])",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Bytes ($net_interface)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "net_interface",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(roger_net_rx_bytes{interface=\"$net_interface\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(roger_net_tx_bytes{interface=\"$net_interface\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Packets ($net_interface)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "net_interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(roger_net_rx_packets{interface=\"$net_interface\"}[$__rate_interval])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(roger_net_tx_packets{interface=\"$net_interface\"}[$__rate_interval])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Data RX (30d)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(roger_net_rx_bytes{interface=\"wan0\"}[30d])",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Data TX (30d)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(roger_net_tx_bytes{interface=\"wan0\"}[30d])",
     "legendFormat": "tx"
    }
   ]
  }
 ]
}